//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMPROJEDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Satis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Satis()
        {
            this.Tbl_SatisUrunDetay = new HashSet<Tbl_SatisUrunDetay>();
        }
    
        public int SatisID { get; set; }
        public int SatisYapanKisi { get; set; }
        public int Firma { get; set; }
        public decimal Kdv { get; set; }
        public System.DateTime Tarih { get; set; }
        public decimal KdvDahilFiyat { get; set; }
        public decimal KdvsizFiyat { get; set; }
    
        public virtual Tbl_Firma Tbl_Firma { get; set; }
        public virtual Tbl_Kullanici Tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SatisUrunDetay> Tbl_SatisUrunDetay { get; set; }
    }
}
