//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMPROJEDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Firma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Firma()
        {
            this.Tbl_Satis = new HashSet<Tbl_Satis>();
        }
    
        public int FirmaID { get; set; }
        public string Adi { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNumarasi { get; set; }
        public Nullable<int> MusteriTemsilcisi { get; set; }
    
        public virtual Tbl_Kullanici Tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satis> Tbl_Satis { get; set; }
    }
}
