//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMPROJEDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Urun()
        {
            this.Tbl_SatisUrunDetay = new HashSet<Tbl_SatisUrunDetay>();
        }
    
        public int UrunID { get; set; }
        public int UrunKategoriID { get; set; }
        public string Adi { get; set; }
        public decimal Fiyat { get; set; }
        public string Aciklama { get; set; }
        public string Fotograf { get; set; }
        public Nullable<int> Urunmiktari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SatisUrunDetay> Tbl_SatisUrunDetay { get; set; }
        public virtual Tbl_UrunKategori Tbl_UrunKategori { get; set; }
    }
}
